name: "Love 2D"

on: ["push"]

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    if: "startsWith(github.ref, 'refs/tags/v')"

    steps:
    - uses: "actions/checkout@v4"

    - name: "Get version"
      id: "get_version"
      run: 'echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}'

    - name: "Build package"
      run: "bash pkg"

    - name: "Name package"
      run: |
        export GAME=${{ format('game-{0}.love', steps.get_version.outputs.VERSION) }}
        mv game.love $GAME

    - name: "Create release"
      uses: "softprops/action-gh-release@v1"
      id: "create_release"
      with:
        name: "${{ steps.get_version.outputs.VERSION }}"
        tag_name: "${{ steps.get_version.outputs.VERSION }}"
        files: "game-${{ steps.get_version.outputs.VERSION }}.love"
        prerelease: true

    - name: "Upload to Discord"
      run: |
        export GAME=${{ format('game-{0}.love', steps.get_version.outputs.VERSION) }}
        curl -F file=@$GAME ${{ secrets.DISCORD_WEBHOOK }}
